### ISSUE TITLE
Possibilities?

### ISSUE THREAD

**Issue by Blueforcer** [untocodes/lenovo-cube-hacking#1]
Just a quick question:
What meaningful things can we do so far?
Can we already install our own APKs? I want to write my own app for that thing:)

**Comment by untocodes** [comment]
Hello.
Currently you cant't install APK's due to the Google firmware doing checks.

We managed to bypass AVB (the boot verification) and the Mediatek flash interface (so you can flash anything on the device).

Currently we are looking into debugging the device with an special cable. (Its sold by Lenovo, but we have a good guess on the pinout so we will try to make one soon)

After that we should proceed to working on TWRP and possibly an android build in the future.

If you want to discuss this in more detail feel free to DM me in Discord: ``Unto#0001``

**Comment by Blueforcer** [comment]
Nice, just sent you a friend request

**Comment by MrHappy** [comment]
Did you get installing apk's on this device working?
